# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17nVKLjf3LF7UTMlS5tUV_ez7f0yWED8-
"""

# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Read CSV File

# Replace with your uploaded file name if needed
df = pd.read_csv('/content/Student Marks.csv')

# Display Dataset
print(df.head())

df['Marks'] = pd.to_numeric(df['Marks'], errors='coerce')

# Remove rows with invalid/missing marks
df = df.dropna(subset=['Marks'])

# Categorize Marks

def categorize_marks(mark):
    if mark > 40:
        return 'Above 40'
    elif 30 <= mark <= 40:
        return '30-40'
    elif 20 <= mark < 30:
        return '20-30'
    else:
        return 'Below 20'

df['Category'] = df['Marks'].apply(categorize_marks)

# Display Updated Data
print(df)

# Count Students in Each Category

grouped_data = df['Category'].value_counts()

print(grouped_data)

# Visualization using Matplotlib

grouped_data.plot(
    kind='bar',
    figsize=(8,5)
)

plt.title('Student Marks Distribution')
plt.xlabel('Marks Category')
plt.ylabel('Number of Students')
plt.xticks(rotation=0)

plt.show()

# Visualization using Seaborn

plt.figure(figsize=(8,5))

sns.countplot(
    x='Category',
    data=df,
    order=['Above 40', '30-40', '20-30', 'Below 20']
)

plt.title('Student Marks Categories')
plt.xlabel('Marks Range')
plt.ylabel('Student Count')

plt.show()